import Foundation

/// One independently reconstructed pointer path for a retained recording
/// segment. Deleted source movement is never replayed; `ProjectPointerTrack`
/// joins the two retained endpoints in the final output clock instead.
public struct ProjectPointerTrackSegment: Equatable, Identifiable, Sendable {
    public let id: UUID
    public let outputRange: MediaTimeRange
    public let track: PointerTrack
    /// Cached once when the retained segment is built. Cut-bridge evaluation
    /// runs for every preview/export frame and must not rescan a long event
    /// array merely to discover when the first click occurs.
    public let firstClickTime: TimeInterval?

    public init(
        id: UUID,
        outputRange: MediaTimeRange,
        track: PointerTrack
    ) {
        self.id = id
        self.outputRange = outputRange
        self.track = track
        firstClickTime = track.events.first {
            $0.time >= outputRange.start
                && ($0.kind == .leftClick || $0.kind == .rightClick)
        }?.time
    }
}

private struct AutomaticCameraFocusCacheKey: Hashable {
    let clipID: UUID
    let startTime: TimeInterval
    let endTime: TimeInterval
    let scale: Double
    let focusX: Double
    let focusY: Double
    let enterDuration: TimeInterval
    let screenStyle: String
    let mass: Double
    let stiffness: Double
    let damping: Double
}

private struct AutomaticCameraFocusSample: Sendable {
    let time: TimeInterval
    let focus: NormalizedPoint
}

/// Pointer evaluator in the final output-time domain.
///
/// `TimelineMap` first maps source events into retained segment clocks and
/// injects a position seed at each cut. This wrapper delegates smoothing and
/// visibility to `PointerTrack`, then adds a short output-time endpoint bridge
/// at an edit so the synthetic cursor does not teleport between retained clips.
public struct ProjectPointerTrack: Equatable, Sendable {
    /// CUR-005: long enough to read as a deliberate move, short enough not to
    /// hide the first action in the retained clip. A click inside this window
    /// shortens the bridge so its recorded position remains exact.
    private static let cutBridgeDuration: TimeInterval = 0.28
    private static let endpointEpsilon: TimeInterval = 1.0 / 10_000.0

    public let segments: [ProjectPointerTrackSegment]
    /// Playback commonly needs the active clip plus its predecessor. Four LRU
    /// entries preserve that locality while discarding transient spring
    /// variants generated by continuous inspector edits.
    private let automaticCameraFocusCache: BoundedMemoizationCache<
        AutomaticCameraFocusCacheKey,
        [AutomaticCameraFocusSample]
    >

    public init(timelineMap: TimelineMap, sourceEvents: [PointerEventRecord]) {
        segments = timelineMap.mapPointerEventSegments(sourceEvents).map {
            ProjectPointerTrackSegment(
                id: $0.id,
                outputRange: $0.outputRange,
                track: PointerTrack($0.events)
            )
        }
        automaticCameraFocusCache = BoundedMemoizationCache(capacity: 4)
    }

    public static func == (lhs: ProjectPointerTrack, rhs: ProjectPointerTrack) -> Bool {
        lhs.segments == rhs.segments
    }

    /// Prepares each retained segment's current spring path on a background
    /// task before the display link asks for its first pointer sample.
    public func prewarmCursorSpring(motion: MotionStyle) {
        guard motion.cursor == .smooth else { return }
        for segment in segments {
            guard !Task<Never, Never>.isCancelled else { return }
            segment.track.prewarmCursorSpring(motion: motion)
        }
    }

    public func evaluation(
        at outputTime: TimeInterval,
        motion: MotionStyle = MotionStyle(),
        style: CursorStyle = CursorStyle()
    ) -> PointerTrackEvaluation {
        guard let segmentIndex = segmentIndex(at: outputTime) else {
            return PointerTrackEvaluation(position: nil, cursor: nil)
        }
        let segment = segments[segmentIndex]
        let current = segment.track.evaluation(
            at: outputTime,
            motion: motion,
            style: style
        )
        guard segmentIndex > segments.startIndex,
              let bridgedPosition = cutBridgePosition(
                  at: outputTime,
                  segmentIndex: segmentIndex,
                  motion: motion,
                  style: style
              ) else {
            return current
        }
        var bridgedCursor = current.cursor
        bridgedCursor?.location = bridgedPosition
        return PointerTrackEvaluation(
            position: bridgedPosition,
            cursor: bridgedCursor
        )
    }

    public func sample(
        at outputTime: TimeInterval,
        motion: MotionStyle = MotionStyle(),
        style: CursorStyle = CursorStyle()
    ) -> PointerSample? {
        evaluation(at: outputTime, motion: motion, style: style).cursor
    }

    /// Stable-region camera following. The camera keeps its latest target while
    /// the pointer remains inside a central rest area. Only a real departure
    /// updates the affected target axis; the screen spring owns the transition.
    public func automaticCameraFocus(
        at outputTime: TimeInterval,
        clip: ZoomAnimationClip,
        motion: MotionStyle = MotionStyle()
    ) -> NormalizedPoint {
        let baseFocus = clip.focus.constrained(to: ZoomViewportTransform.focusEdgeInset)
        guard clip.origin == .automatic,
              outputTime.isFinite,
              clip.endTime > clip.startTime else {
            return baseFocus
        }
        let key = AutomaticCameraFocusCacheKey(
            clipID: clip.id,
            startTime: clip.startTime,
            endTime: clip.endTime,
            scale: clip.scale,
            focusX: baseFocus.x,
            focusY: baseFocus.y,
            enterDuration: clip.enterDuration,
            screenStyle: motion.screen.rawValue,
            mass: motion.screenSpringMass,
            stiffness: motion.screenSpringStiffness,
            damping: motion.screenSpringDamping
        )
        let samples = automaticCameraFocusCache.value(for: key) {
            makeAutomaticCameraFocusSamples(
                clip: clip,
                baseFocus: baseFocus,
                motion: motion
            )
        }
        return interpolatedAutomaticCameraFocus(
            at: min(max(outputTime, clip.startTime), clip.endTime),
            samples: samples,
            fallback: baseFocus
        )
    }

    private func makeAutomaticCameraFocusSamples(
        clip: ZoomAnimationClip,
        baseFocus: NormalizedPoint,
        motion: MotionStyle
    ) -> [AutomaticCameraFocusSample] {
        let interval = 1.0 / 120.0
        let visibleHalfSpan = 1 / (2 * max(clip.scale, 1))
        let restAreaInsetRatio = 0.22
        let restAreaHalfSpan = max(
            visibleHalfSpan - (2 * visibleHalfSpan) * restAreaInsetRatio,
            0.01
        )
        let followStart = min(
            clip.startTime + min(max(clip.enterDuration, 0), clip.duration),
            clip.endTime
        )
        let mass = max(motion.screenSpringMass, 0.01)
        let stiffness = max(motion.screenSpringStiffness, 0.01)
        let damping = max(motion.screenSpringDamping, 0.01)

        var position = baseFocus
        var target = baseFocus
        var velocityX = 0.0
        var velocityY = 0.0
        let clipEvents = events(from: clip.startTime, through: clip.endTime)
        var sampleTime = clip.startTime
        var result = [AutomaticCameraFocusSample(time: sampleTime, focus: position)]
        result.reserveCapacity(max(Int(clip.duration / interval) + 2, 1))

        while sampleTime < clip.endTime {
            let nextTime = min(sampleTime + interval, clip.endTime)
            if nextTime >= followStart,
               let cursor = Self.interpolatedRawPosition(at: nextTime, in: clipEvents) {
                if cursor.x < target.x - restAreaHalfSpan
                    || cursor.x > target.x + restAreaHalfSpan {
                    target.x = cursor.x
                }
                if cursor.y < target.y - restAreaHalfSpan
                    || cursor.y > target.y + restAreaHalfSpan {
                    target.y = cursor.y
                }
                target = target.constrained(to: ZoomViewportTransform.focusEdgeInset)
            }

            let deltaTime = max(nextTime - sampleTime, 0)
            let accelerationX = (
                stiffness * (target.x - position.x) - damping * velocityX
            ) / mass
            let accelerationY = (
                stiffness * (target.y - position.y) - damping * velocityY
            ) / mass
            velocityX += accelerationX * deltaTime
            velocityY += accelerationY * deltaTime
            position = NormalizedPoint(
                x: position.x + velocityX * deltaTime,
                y: position.y + velocityY * deltaTime
            ).constrained(to: ZoomViewportTransform.focusEdgeInset)
            sampleTime = nextTime
            result.append(AutomaticCameraFocusSample(time: sampleTime, focus: position))
        }
        return result
    }

    /// Raw linear interpolation over the recorded event stream. Click and
    /// move samples both carry real pointer positions; between samples the
    /// position is a straight ramp, never a replayed stale event.
    private static func interpolatedRawPosition(
        at time: TimeInterval,
        in events: [PointerEventRecord]
    ) -> NormalizedPoint? {
        guard let first = events.first else { return nil }
        if time <= first.time { return first.location }
        guard let last = events.last, time < last.time else {
            return events.last?.location
        }
        var lower = events.startIndex
        var upper = events.endIndex
        while lower < upper {
            let middle = lower + (upper - lower) / 2
            if events[middle].time <= time {
                lower = middle + 1
            } else {
                upper = middle
            }
        }
        let upperIndex = min(lower, events.index(before: events.endIndex))
        let lowerIndex = max(upperIndex - 1, events.startIndex)
        let a = events[lowerIndex]
        let b = events[upperIndex]
        let duration = max(b.time - a.time, .leastNonzeroMagnitude)
        let progress = min(max((time - a.time) / duration, 0), 1)
        return NormalizedPoint(
            x: a.location.x + (b.location.x - a.location.x) * progress,
            y: a.location.y + (b.location.y - a.location.y) * progress
        )
    }

    private func interpolatedAutomaticCameraFocus(
        at time: TimeInterval,
        samples: [AutomaticCameraFocusSample],
        fallback: NormalizedPoint
    ) -> NormalizedPoint {
        guard let first = samples.first else { return fallback }
        guard time > first.time else { return first.focus }
        guard let last = samples.last, time < last.time else { return samples.last?.focus ?? fallback }

        var lower = samples.startIndex
        var upper = samples.endIndex
        while lower < upper {
            let middle = lower + (upper - lower) / 2
            if samples[middle].time <= time {
                lower = middle + 1
            } else {
                upper = middle
            }
        }
        let upperIndex = min(lower, samples.index(before: samples.endIndex))
        let lowerIndex = max(upperIndex - 1, samples.startIndex)
        let a = samples[lowerIndex]
        let b = samples[upperIndex]
        let duration = max(b.time - a.time, .leastNonzeroMagnitude)
        let progress = min(max((time - a.time) / duration, 0), 1)
        return NormalizedPoint(
            x: a.focus.x + (b.focus.x - a.focus.x) * progress,
            y: a.focus.y + (b.focus.y - a.focus.y) * progress
        )
    }

    private func events(
        from start: TimeInterval,
        through end: TimeInterval
    ) -> [PointerEventRecord] {
        var result: [PointerEventRecord] = []
        for segment in segments {
            let events = segment.track.events(from: start, through: end)
            result.append(contentsOf: events)
        }
        return result
    }

    /// CUR-005: connect only the retained endpoints. The deleted source path
    /// remains absent, unlike a naive interpolation on the original source
    /// clock. Quintic smootherstep gives zero velocity and acceleration at
    /// both ends, avoiding the conspicuous constant-speed cut transition.
    private func cutBridgePosition(
        at time: TimeInterval,
        segmentIndex: Int,
        motion: MotionStyle,
        style: CursorStyle
    ) -> NormalizedPoint? {
        let segment = segments[segmentIndex]
        let start = segment.outputRange.start
        guard time >= start else { return nil }

        let availableUntilClick = segment.firstClickTime.map { max($0 - start, 0) }
        let duration = min(
            min(
                Self.cutBridgeDuration,
                availableUntilClick ?? Self.cutBridgeDuration
            ),
            segment.outputRange.duration
        )
        guard duration > Self.endpointEpsilon,
              time < start + duration else { return nil }

        let previous = segments[segmentIndex - 1]
        let previousTime = max(
            previous.outputRange.start,
            previous.outputRange.end - Self.endpointEpsilon
        )
        guard let from = previous.track.evaluation(
            at: previousTime,
            motion: motion,
            style: style
        ).position,
        let to = segment.track.evaluation(
            at: start + duration,
            motion: motion,
            style: style
        ).position else { return nil }

        let linear = min(max((time - start) / duration, 0), 1)
        let eased = linear * linear * linear
            * (linear * (linear * 6 - 15) + 10)
        return NormalizedPoint(
            x: from.x + (to.x - from.x) * eased,
            y: from.y + (to.y - from.y) * eased
        )
    }

    private func segmentIndex(at time: TimeInterval) -> Int? {
        guard time.isFinite, time >= 0 else { return nil }
        var lower = segments.startIndex
        var upper = segments.endIndex
        while lower < upper {
            let middle = lower + (upper - lower) / 2
            if segments[middle].outputRange.end <= time {
                lower = middle + 1
            } else {
                upper = middle
            }
        }
        guard lower < segments.endIndex else { return nil }
        let candidate = segments[lower]
        guard time >= candidate.outputRange.start else { return nil }
        return lower
    }
}
